"""empty message

Revision ID: 3425d38949c0
Revises: c62c2acaa549
Create Date: 2024-03-19 22:59:42.404854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3425d38949c0'
down_revision = 'c62c2acaa549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pleadqueries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pleadqueries', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
